const COUNTRY_NAMES: Record<string, { es: string; fr: string }> = {
  AD: { es: 'Andorra', fr: 'Andorre' },
  AL: { es: 'Albania', fr: 'Albanie' },
  AR: { es: 'Argentina', fr: 'Argentine' },
  AT: { es: 'Austria', fr: 'Autriche' },
  AU: { es: 'Australia', fr: 'Australie' },
  BE: { es: 'Bélgica', fr: 'Belgique' },
  BG: { es: 'Bulgaria', fr: 'Bulgarie' },
  BO: { es: 'Bolivia', fr: 'Bolivie' },
  BR: { es: 'Brasil', fr: 'Brésil' },
  CA: { es: 'Canadá', fr: 'Canada' },
  CH: { es: 'Suiza', fr: 'Suisse' },
  CL: { es: 'Chile', fr: 'Chili' },
  CN: { es: 'China', fr: 'Chine' },
  CO: { es: 'Colombia', fr: 'Colombie' },
  CR: { es: 'Costa Rica', fr: 'Costa Rica' },
  CU: { es: 'Cuba', fr: 'Cuba' },
  CZ: { es: 'Chequia', fr: 'Tchéquie' },
  DE: { es: 'Alemania', fr: 'Allemagne' },
  DK: { es: 'Dinamarca', fr: 'Danemark' },
  DZ: { es: 'Argelia', fr: 'Algérie' },
  EC: { es: 'Ecuador', fr: 'Équateur' },
  EG: { es: 'Egipto', fr: 'Égypte' },
  ES: { es: 'España', fr: 'Espagne' },
  FI: { es: 'Finlandia', fr: 'Finlande' },
  FR: { es: 'Francia', fr: 'France' },
  GB: { es: 'Reino Unido', fr: 'Royaume-Uni' },
  GR: { es: 'Grecia', fr: 'Grèce' },
  GT: { es: 'Guatemala', fr: 'Guatemala' },
  HR: { es: 'Croacia', fr: 'Croatie' },
  HU: { es: 'Hungría', fr: 'Hongrie' },
  IE: { es: 'Irlanda', fr: 'Irlande' },
  IL: { es: 'Israel', fr: 'Israël' },
  IN: { es: 'India', fr: 'Inde' },
  IS: { es: 'Islandia', fr: 'Islande' },
  IT: { es: 'Italia', fr: 'Italie' },
  JP: { es: 'Japón', fr: 'Japon' },
  KE: { es: 'Kenia', fr: 'Kenya' },
  KR: { es: 'Corea del Sur', fr: 'Corée du Sud' },
  LU: { es: 'Luxemburgo', fr: 'Luxembourg' },
  MA: { es: 'Marruecos', fr: 'Maroc' },
  MX: { es: 'México', fr: 'Mexique' },
  NL: { es: 'Países Bajos', fr: 'Pays-Bas' },
  NO: { es: 'Noruega', fr: 'Norvège' },
  NZ: { es: 'Nueva Zelanda', fr: 'Nouvelle-Zélande' },
  PA: { es: 'Panamá', fr: 'Panama' },
  PE: { es: 'Perú', fr: 'Pérou' },
  PH: { es: 'Filipinas', fr: 'Philippines' },
  PL: { es: 'Polonia', fr: 'Pologne' },
  PT: { es: 'Portugal', fr: 'Portugal' },
  PY: { es: 'Paraguay', fr: 'Paraguay' },
  RO: { es: 'Rumanía', fr: 'Roumanie' },
  SE: { es: 'Suecia', fr: 'Suède' },
  SN: { es: 'Senegal', fr: 'Sénégal' },
  TH: { es: 'Tailandia', fr: 'Thaïlande' },
  TN: { es: 'Túnez', fr: 'Tunisie' },
  TR: { es: 'Turquía', fr: 'Turquie' },
  US: { es: 'Estados Unidos', fr: 'États-Unis' },
  UY: { es: 'Uruguay', fr: 'Uruguay' },
  VE: { es: 'Venezuela', fr: 'Venezuela' },
  VN: { es: 'Vietnam', fr: 'Viêt Nam' },
  ZA: { es: 'Sudáfrica', fr: 'Afrique du Sud' },
};

export function getCountryName(code: string, lang: 'es' | 'fr'): string {
  return COUNTRY_NAMES[code]?.[lang] || code;
}
